"""add audit_logs user_id fk

Revision ID: df3cf6adbab3
Revises: ad367512aefc
Create Date: 2026-07-24 15:32:56.701903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df3cf6adbab3'
down_revision: Union[str, None] = 'ad367512aefc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_audit_logs_user_id', 'users', ['user_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_audit_logs_user_id', type_='foreignkey')

    # ### end Alembic commands ###
